version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - migration
      - db

  migration:
      build:
        context: .
        dockerfile: Dockerfile.migration
      container_name: migrations
      depends_on:
        - db
