version: '3.8'
services:

  postgres_db:
    image: postgres:10.16
    container_name: postgres_db
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  web:
    build: .
    command: gunicorn djangoProject.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - migration
      - postgres_db

  migration:
      build:
        context: .
        dockerfile: Dockerfile.migration
      container_name: migrations
      env_file:
        - .env
      depends_on:
        - postgres_db
